version: '3'
services:
  restApi:
    image: prasilabs/smartsettings:latest
    container_name: restApi-container
    expose:
      - 8080
      - 8443
      - 80
      - 443
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=smartuser
      - MONGODB_PASSWORD=smarts3cr3t
    links:
      - mongodb:mongodb
    restart: always
    depends_on:
      - mongousercreator
    volumes:
      - ./ssl/:/etc/ssl/

  mongodb:
    image: mongo
    container_name: mongo-container
    expose:
      - 27017
    networks:
      - default
    volumes:
      - data-volume:/data/db
    ports:
      - '27017:27017'

  mongousercreator:
    image: mongo
    container_name: mongo-user-creator
    links:
      - mongodb:mongodb
    command: mongo --host mongodb --eval  "db.getSiblingDB('smartsettings').createUser({user:'smartuser', pwd:'smarts3cr3t', roles:[{role:'readWrite',db:'smartsettings'}]});"
    depends_on:
      - mongodb

volumes:
  data-volume: