version: '3'
services:
  restApi:
    image: prasilabs/smartsettings:latest
    container_name: restApi-container
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    links:
      - mongodb:mongodb
    restart: always
    depends_on:
      - mongousercreator

  mongodb:
    image: mongo
    container_name: mongo-container
    expose:
      - 27017
    networks:
      - default
    volumes:
      - data-volume:/data/db
    ports:
      - '27017:27017'

  mongousercreator:
    image: mongo
    container_name: mongo-user-creator
    links:
      - mongodb:mongodb
    command: mongo --host mongodb --eval  "db.getSiblingDB('smartsettings').createUser({user:'smartuser', pwd:'smarts3cr3t', roles:[{role:'readWrite',db:'smartsettings'}]});"
    depends_on:
      - mongodb

volumes:
  data-volume: