@startuml

class ContextData {

}

abstract class SmartSetting<T extends ContextData> {
    - boolean isRunning
    + boolean isRunning()
    + void start()
    + void stop()
    # abstract void applySettingChanges()
    # abstract Listener<T> getListener()
    # abstract void isCriteriaMatching(ContextData<T> contextData)
    + abstract View getView(Context context)
    + abstract void askSettingChangePermissionIfAny((Boolean))
    - void startListenForContextChanges((T))
    - void stopListeningToContextChanges()
}

abstract class Listener<T extends ContextData> {
    # abstract void startListenForContextChanges((Boolean))
    # abstract void stopListeningToContextChanges()
    + abstract void askListeningPermissionIfAny()
    - onContextChange(T contextData)
}

SmartSetting *-- Listener

SmartSetting .. ContextData : listens to contextData

interface SmartSettingProvider {
    + View getInputView((SmartSetting))
}

SmartSettingProvider .. SmartSetting

class SmartProfile <<(S,red) Singleton>> {
    - Map<SmartSetting, Boolean> smartSettings
    + void enableSmartSetting(SmartSetting smartSetting)
    + void disableSmartSetting(SmartSetting smartSetting)
    + Map<SmartSetting, Boolean> getSmartSettings()
    - void persistSmartSettingToMemory()
    - void reInitializeSmartSettingsFromMemory()
}

note right of SmartProfile
Singleton object.
end note

SmartProfile o-- SmartSetting : has List of created smart setting

class SmartSettingChooser {
    - List<SmartSettingProvider> smartSettingProvider;
}

note right of SmartSettingChooser
UI for showing list of smart setting types available.
end note

SmartSettingChooser *-- SmartSettingProvider


class Home {

}

note left of Home {
    App main UI.
}

Home .. SmartProfile : enables/diabled smartSetting
Home o-- SmartSettingChooser : asks to provide SmartSetting

class MainService<<(S,red) Singleton>> {
    - void startSmartSettings()
    - void stopSmartSettings()
}

note left of MainService
Never ending non ui process
end note

MainService .. SmartProfile : start/stop the smartSettings

Home .. MainService : Starts service

class SmartSettingRepository {
    + void getSmartSettings()
}

SmartProfile o-- SmartSettingRepository

@enduml