@startuml

SmartSetting -> ContextListener : Ask Permissions
ContextListener -> SmartSetting : Permission Granted
SmartSetting -> SettingChanger : Ask Permissions
SettingChanger -> SmartSetting : Permission Granted
SmartSetting -> ContextListener : Listen to Context Change
ContextListener --> ContextListener : If Criteria Matches
ContextListener -> SmartSetting : Criteria Matched
SmartSetting -> SettingChanger : Apply Changes
SmartSetting -> AndroidSetting : Apply

@enduml